### PR TITLE
[feat] add localization to VoiceContent mod

### PR DESCRIPTION
**Pull request by leonardomurakami**
Also first time making a mod here, so I may have made a few mistakes.
Just wanted to make possible for non-english speaking gamers to utilize your mod too.
(also open to feedback if this is non-efficient or anything as such)

Does the VoiceRecognitionAPI utilize system language for recognition?

### CODE REVIEW

**Comment by NotestQ** [comment]
> Does the VoiceRecognitionAPI utilize system language for recognition?

Yes it does! From testing it uses the system's display language, though it seems it is [not available for pt-BR](https://support.microsoft.com/en-us/windows/windows-speech-recognition-commands-9d25ef36-994d-f367-a81a-a326160128c7)
One of my testers wasn't able to test the mod properly because their display language was set to portuguese, so that might not be a possible translation unless players purposefully change their display language. Albeit portuguese is my native language my computer's display language was set to english, so I got lucky on that regard

> Just wanted to make possible for non-english speaking gamers to utilize your mod too.

Thank you! I'll try to test it soon enough, maybe one of the available languages can get "good enough" pt-BR recognition

**Comment by leonardomurakami** [comment]
Oh cool, didn't knew Windows Speech Recognition did not support pt-BR, always assumed it did due to games like phasmophobia utilizing WSR afaik.

> Thank you! I'll try to test it soon enough, maybe one of the available languages can get "good enough" pt-BR recognition

But adding another language is also completely possible. Even if not pt-BR, maybe spanish or french seems like good additions.
(not that I am capable, in any way, of adding these)

**Comment by NotestQ** [comment]
Looks like Phasmophobia uses [Vosk](https://alphacephei.com/vosk/) as their main speech recognition library! (and WSR as an option) It's available for C# so I'll see what I can do with it, thanks for bringing my attention to it!

**Comment by NotestQ** [comment]
lgtm, pulled prematurely since a Vosk voice recognition API will take a bit to make and I'm rewriting parts of the mod

**Pull request merged**
